### ISSUE TITLE
Demo link doesn't work

### ISSUE THREAD

**Issue by vedant1811** [mmazzarolo/img-resizable#2]
:(

**Comment by mmazzarolo** [comment]
Hey!
The demo [is working for me now](http://mazzarolomatteo.com/polymer/img-resizable-demo/).  
It was probably just an hosting issue 👍

**Comment by vedant1811** [comment]
![image](https://cloud.githubusercontent.com/assets/3260363/16794619/a0272136-48f6-11e6-872e-bd7c30263baa.png)

not working

**Comment by mmazzarolo** [comment]
![schermata 2016-07-13 alle 09 14 47](https://cloud.githubusercontent.com/assets/9536354/16794808/501aa6c0-48da-11e6-87a7-d9e65ad8fb3f.png)
I guess the hosting is not reachable from your country then, I'm sorry.  
Anyway you can easily drop this component in your project and give it a test :)
